export default [
  {
    id: 1,
    companyName: 'Alliance Software Incorporation',
    tags: ['Computer Science', 'OJT'],
    address1: 'Kamputhaw, Cebu City, Cebu',
    address2: '9F Ayala Center Cebu Tower, Bohol St., Cebu Business Park',
    yearEstablished: 2016,
    employeeMin: 1001,
    employeeMax: 5000,
    datePosted: '3 days ago',
    contactEmail: 'hr@alliancesoftwareincorporation.com',
  },
  {
    id: 2,
    companyName: 'Accenture Incorporation',
    tags: ['Computer Science', 'OJT'],
    address1: 'Mandaluyong City, Metro Manila',
    address2: '6750 Ayala Avenue, Makati City, Metro Manila',
    yearEstablished: 1989,
    employeeMin: 10001,
    employeeMax: 50000,
    datePosted: '40 days ago',
    contactEmail: 'hr@accentureincorporation.com',
  },
  {
    id: 3,
    companyName: 'Google Incorporation',
    tags: ['Computer Science', 'OJT'],
    address1: 'Mountain View, California',
    address2: '1600 Amphitheatre Parkway, Mountain View, California',
    yearEstablished: 1998,
    employeeMin: 10001,
    employeeMax: 50000,
    datePosted: '16 days ago',
    contactEmail: 'hr@google.com',
  },
  {
    id: 4,
    companyName: 'Facebook Incorporation',
    tags: ['Computer Science', 'OJT'],
    address1: 'Menlo Park, California',
    address2: '1 Hacker Way, Menlo Park, California',
    yearEstablished: 2004,
    employeeMin: 10001,
    employeeMax: 50000,
    datePosted: '32 days ago',
    contactEmail: 'hr@faceboook.com',
  },
  {
    id: 5,
    companyName: 'Amazon Incorporation',
    tags: ['Computer Science', 'OJT'],
    address1: 'Seattle, Washington',
    address2: '410 Terry Ave N, Seattle, Washington',
    yearEstablished: 1994,
    employeeMin: 10001,
    employeeMax: 50000,
    datePosted: '25 days ago',
    contactEmail: 'hr@amazon.com',
  },
];
