const requirements = [
  {
    id: 1,
    title: 'Study Load',
    description: 'Attach your Memorandum of Agreement (MOA)',
    referenceLink: 'https://www.google.com',
    isComplete: true,
    dueDate: '2024-03-24T01:00:00.000Z',
  },
  {
    id: 2,
    title: 'Endorsement Letter',
    description: 'Attach your Memorandum of Agreement (MOA)',
    referenceLink: 'https://www.google.com',
    isComplete: false,
    dueDate: '2024-04-01T01:00:00.000Z',
  },
  {
    id: 3,
    title: 'Confirmation Letter',
    description: 'Attach your Memorandum of Agreement (MOA)',
    referenceLink: 'https://www.google.com',
    isComplete: false,
    dueDate: '2024-03-31T01:00:00.000Z',
  },
  {
    id: 4,
    title: 'Waiver',
    description: 'Attach your Memorandum of Agreement (MOA)',
    referenceLink: 'https://www.google.com',
    isComplete: false,
    dueDate: '2024-12-31T01:00:00.000Z',
  },
  {
    id: 5,
    title: 'DOU',
    description: 'Attach your Memorandum of Agreement (MOA)',
    referenceLink: 'https://www.google.com',
    isComplete: true,
    dueDate: '2024-12-31T01:00:00.000Z',
  },
  {
    id: 6,
    title: 'Memorandum of Agreement (MOA)',
    description: 'Attach your Memorandum of Agreement (MOA)',
    referenceLink: 'https://www.google.com',
    isComplete: false,
    dueDate: '2024-12-31T01:00:00.000Z',
  },
  {
    id: 7,
    title: 'Logbook',
    description: 'Attach your Memorandum of Agreement (MOA)',
    referenceLink: 'https://www.google.com',
    isComplete: false,
    dueDate: '2024-12-31T01:00:00.000Z',
  },
  {
    id: 8,
    title: 'Digital Portfolio',
    description: 'Attach your Memorandum of Agreement (MOA)',
    referenceLink: 'https://www.google.com',
    isComplete: false,
    dueDate: '2024-12-31T01:00:00.000Z',
  },
];

export default requirements;
